services:
  postgres:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: predictelection
